#!/bin/bash
#SBATCH --account=Sis22_laio_0
#SBATCH --partition=m100_usr_prod
#SBATCH --qos=normal
#SBATCH --qos=m100_qos_dbg          	
#SBATCH --nodes=1
#SBATCH --time=0:58:00             		#format: HH:MM:SS
#SBATCH --ntasks-per-node=1        		#4 tasks uso una sola cpu (SMT)
#SBATCH --cpus-per-task=32        		#128cpu/nodo 64x2 socket
##SBATCH --gres=gpu:1            			#1 gpus per node out of 4
#SBATCH --mem=32000                		#memory per node out of 256000MB
#SBATCH --job-name=intrinsic_dim

#source module_load
module load profile/deeplrn
module load autoload cineca-ai/2.1.0
export OMP_NUM_THREADS=16
#conda activate /m100_work/Sis22_ermut/ddoimo/intrinsic_dimenson/gride

srun  -N1 python3 real_tests.py --algo 'geomle' --k1 5 --k2 15  #--data_folder '/m100_work/Sis22_ermut/ddoimo/intrinsic_dimension/datasets'
